# Generated by Django 4.0.5 on 2022-06-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('protocol_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(blank=True)),
                ('current_status', models.CharField(blank=True, max_length=50)),
                ('tasks_done', models.TextField(blank=True)),
                ('tasks_pending', models.TextField(blank=True)),
                ('nodes_st', models.CharField(blank=True, max_length=100)),
                ('testnet_st', models.CharField(blank=True, max_length=100)),
                ('mainnet_st', models.CharField(blank=True, max_length=100)),
                ('transactions_st', models.CharField(blank=True, max_length=100)),
                ('performer_1', models.CharField(blank=True, max_length=50)),
                ('performer_2', models.CharField(blank=True, max_length=50)),
                ('last_comment', models.TextField(blank=True)),
            ],
        ),
    ]
