# Generated by Django 4.0.5 on 2022-06-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='current_status',
        ),
        migrations.AddField(
            model_name='protocol',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='start_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
