# Generated by Django 4.0.5 on 2022-06-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_remove_protocol_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='active_status',
            field=models.BooleanField(blank=True),
        ),
    ]
