# Generated by Django 4.0.5 on 2022-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_rename_testnet_st_protocol_testing_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
